#!/usr/bin/env python3
"""Regenerate _project-papers.qmd from bib/knight-project.bib.

Run automatically as a Quarto project pre-render hook (see _quarto.yml), so
editing the .bib file and re-rendering/previewing the site is enough to
update the "Project papers & preprints" section on publications.qmd -- no
manual qmd edits needed.
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BIB_PATH = REPO_ROOT / "bib" / "knight-project.bib"
OUT_PATH = REPO_ROOT / "_project-papers.qmd"


def split_top_level(text, sep=","):
    """Split text on sep, ignoring separators nested inside {}."""
    parts, depth, current = [], 0, []
    for ch in text:
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
        if ch == sep and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current))
    return parts


ACRONYM_FIXES = {
    "NEUKRAG": "NeuKRAG",
    "LLMS": "LLMs",
}


def strip_braces(value):
    value = re.sub(r"\s+", " ", value.strip())
    if value.startswith("{") and value.endswith("}"):
        # only strip a fully-wrapping outer pair
        depth = 0
        for i, ch in enumerate(value):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0 and i != len(value) - 1:
                    break
        else:
            value = value[1:-1]
    value = value.replace("{", "").replace("}", "").strip()
    value = value.replace("\\&", "&").replace("\\%", "%").replace("\\_", "_")
    for wrong, right in ACRONYM_FIXES.items():
        value = re.sub(rf"\b{wrong}\b", right, value)
    return value.replace("--", "-")


def parse_bib(text):
    entries = []
    for match in re.finditer(r"@(\w+)\s*\{", text):
        entry_type = match.group(1)
        start = match.end()
        depth = 1
        i = start
        while depth > 0 and i < len(text):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        body = text[start:i - 1]

        key, _, rest = body.partition(",")
        fields = {}
        for chunk in split_top_level(rest):
            if "=" not in chunk:
                continue
            field_name, _, raw_value = chunk.partition("=")
            field_name = field_name.strip().lower()
            fields[field_name] = strip_braces(raw_value.strip().rstrip(","))
        entries.append({"type": entry_type, "key": key.strip(), **fields})
    return entries


def format_authors(raw_author):
    if raw_author.strip().lower() in ("anonymous authors", "research team"):
        return f"**{raw_author.strip()}**"
    names = []
    for person in re.split(r"\s+and\s+", raw_author):
        tokens = person.split()
        if len(tokens) < 2:
            names.append(person)
            continue
        family, given = tokens[-1], tokens[:-1]
        initials = " ".join(w[0].upper() + "." for w in given if w)
        names.append(f"{family}, {initials}")
    return "**" + ", ".join(names) + "**"


def format_venue(entry):
    venue = entry.get("booktitle") or entry.get("journal") or entry.get("note") or ""
    extra = []
    if entry.get("publisher"):
        extra.append(entry["publisher"])
    if entry.get("pages"):
        extra.append(f"pp. {entry['pages']}")
    sentence = venue.rstrip(".")
    if extra:
        sentence += ". " + ", ".join(extra)
    return sentence.rstrip(".") + "."


def format_links(entry):
    links = []
    if entry.get("pdf"):
        links.append(f"[Download PDF]({entry['pdf']})")
    if entry.get("doi"):
        links.append(f"[DOI: {entry['doi']}](https://doi.org/{entry['doi']})")
    elif entry.get("url"):
        links.append(f"[Link]({entry['url']})")
    return links


def render_card(entry):
    lines = ["::: {.thread-card}", f"### {entry.get('title', '')}"]
    lines.append(format_authors(entry.get("author", "")))
    lead = entry.get("institution", "")
    venue = format_venue(entry)
    lines.append(f"{lead}. *{venue}*" if lead else f"*{venue}*")
    lines.append("")
    if entry.get("abstract"):
        lines.append(entry["abstract"])
        lines.append("")
    links = format_links(entry)
    if links:
        lines.append(" - ".join(links))
    else:
        lines.append("*PDF forthcoming.*")
    lines.append(":::")
    return "\n".join(lines)


def main():
    if not BIB_PATH.exists():
        print(f"error: {BIB_PATH} not found", file=sys.stderr)
        return 1
    entries = parse_bib(BIB_PATH.read_text(encoding="utf-8"))
    cards = "\n\n".join(render_card(e) for e in entries)
    header = (
        "<!-- AUTO-GENERATED by scripts/gen_project_papers.py from "
        "bib/knight-project.bib. Do not edit by hand. -->\n\n"
    )
    content = header + cards + "\n"
    # Skip the write if unchanged, so the preview file-watcher doesn't see a
    # spurious change and retrigger an endless rebuild loop.
    if OUT_PATH.exists() and OUT_PATH.read_text(encoding="utf-8") == content:
        print(f"{OUT_PATH} already up to date ({len(entries)} entries)")
        return 0
    OUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {OUT_PATH} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
